name: DevSecOps Pipeline

on: [push, pull_request]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # SAST - Semgrep
      - name: SAST Scan (Semgrep)
        run: |
          pip install semgrep
          semgrep scan --config "p/security-audit" --json -o sast-report.json
        continue-on-error: true

      # SAST - SonarQube
      - name: SAST Scan (SonarQube)
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=hnim71_VAmPI2
            -Dsonar.organization=hnim71

      # SCA - Snyk
      - name: SCA Scan (Snyk)
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      # Quality Gate
      - name: Quality Gate
        run: |
          if [ -f sast-report.json ] && grep -q "ERROR" sast-report.json; then
            echo "::error::Pipeline failed: Security Vulnerabilities found!"
            exit 1
          fi
